<div class="navrow">
	<nav>
		<ul>
		<li><a href="index.php">Home</a></li>
		<li><a href="enquire.php">Product Enquiry</a></li>
		<li><a href="product.php">Product Range </a></li>
		<li><a href="about2.php">About Me</a></li>
		</ul>
	</nav>
		<div class="dropdown">
		<div class="navi">ENHANCEMENT</div>
		<div class="dropdown-content">
		<a href="enhancements.php" class="navi"> ENHANCEMENT 1</a>
		<a href="enhancements2.php" class="navi">ENHANCEMENT 2</a>
		<a href="phpenhancements.php" class="navi">ENHANCEMENT 3</a>
		</div>
	</div>
</div>