<div class="navrow">
	<div class="navcol">
	<a href="index.php" class="navi"> HOME </a>
	</div>
	<div class="navcol">
	<a href="topic.php" class="navi"> SSH </a>
	</div>
	<div class="navcol">
	<a href="quiz.php" class="navi"> QUIZ </a>
	</div>
	<div class="navcol">
	<a href="manage.php" class="navi"> Manage </a>
	</div>
		<div class="dropdown">
		<div class="navi">ENHANCEMENT</div>
		<div class="dropdown-content">
		<a href="enhancements.php" class="navi"> ENHANCEMENT 1</a>
		<a href="enhancements2.php" class="navi">ENHANCEMENT 2</a>
		<a href="phpenhancements.php" class="navi">ENHANCEMENT 3</a>
		</div>
	</div>
</div>